extends Node


@warning_ignore("unused_signal")
signal loopStart()
@warning_ignore("unused_signal")
signal loopEnd()
@warning_ignore("unused_signal")
signal turnStart(place : Place)
@warning_ignore("unused_signal")
signal turnEnd(place : Place)
@warning_ignore("unused_signal")
signal request_event(place_stats: Dictionary, place_type: String)
@warning_ignore("unused_signal")
signal event_triggered(event_data: EventData)
@warning_ignore("unused_signal")
signal reward_received(rewards: Dictionary)
@warning_ignore("unused_signal")
signal startAmbush(nb_bandit : int)
@warning_ignore("unused_signal")
signal endAmbush()
@warning_ignore("unused_signal")
signal get_looted()
